name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
projects: ["SeedsToCommunity/Seedy AI Project"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature here...
    validations:
      required: true
