name: Security Vulnerability
description: Report a security vulnerability
title: "[Security]: "
labels: ["security"]
projects: ["SeedsToCommunity/Seedy AI Project"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the security vulnerability
      placeholder: Describe the vulnerability here...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Instructions
      description: Steps to reproduce the vulnerability
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See vulnerability
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: Select the severity level of this vulnerability
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: true
  - type: textarea
    id: suggested-fix
    attributes:
      label: Suggested Fix
      description: If you have any ideas on how to fix the vulnerability, please share them
      placeholder: Describe a potential fix here...
    validations:
      required: false
